### ISSUE TITLE
Unable to import Kubernetes with latest python Kubernetes client

### ISSUE THREAD

**Issue by Dsiddhesh** [kubernetes-client/python#2097]
**What happened (please include outputs or screenshots)**:
Unable to import Kubernetes with latest python Kubernetes client. 
**What you expected to happen**:

Should be able to import

**How to reproduce it (as minimally and precisely as possible)**:
With Kubernetes client of v 27.2.0 or 26.1.0  if i try to import kubernetes then it gives error like below
Code test.py
```
import kubernetes    
from kubernetes import client
from kubernetes import kubernetes    
print('Hello, world!')
```

`[root@comfort1 ]# python3 test.py /usr/local/lib/python3.6/site-packages/google/auth/crypt/_cryptography_rsa.py:22: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6. import cryptography.exceptions Traceback (most recent call last): File "test.py", line 4, in from kubernetes import kubernetes ImportError: cannot import name 'kubernetes' [root@comfort1 ]#`

**Anything else we need to know?**:
Same code worked with Kubernetes client 25.3.0. I need to upgrade to latest Kubernetes client to resolve a vulnarability

**Environment**:
- Kubernetes version (`kubectl version`): 26.1.0, 27.2.0
- OS (e.g., MacOS 10.13.6): RHEL 8
- Python version (`python --version`) 3.6.8
- Python client version (`pip list | grep kubernetes`)   kubernetes              27.2.0

**Comment by yliaog** [comment]
i can use the client 27.2.0 with python 3.9.1 without any issue.

after the installation, the examples given below can be run successfully.
https://github.com/kubernetes-client/python#examples

**Comment by curiousEnough** [comment]
I am having the same issues with 
kubernetes               19.15.0
