### ISSUE TITLE
'V1Node' object has no attribute '__getitem__' after upgrading to k8s 1.11.2

### ISSUE THREAD

**Issue by 2rs2ts** [kubernetes-client/python#622]
We are using version 7.0.0 of this library.

Our code does this:

```python
def node_is_cordoned(node_name, api_client):
    node = api_client.read_node(node_name)
    return node['spec']['unschedulable']
```

When we pass the name of a node that's cordoned we get this error: `TypeError: 'V1Node' object has no attribute '__getitem__'`

The funny thing is that this only happened after we upgraded from k8s 1.10.5 to 1.11.2. As I understand it, 7.0.0 should be compatible with both of these versions. What happened?

**Comment by micw523** [comment]
I believe you should use ```node.spec``` instead since node is a V1Node object but not a dictionary?

I have no idea why it has functioned before.
